### ISSUE TITLE
프로젝트 생성하기

### ISSUE THREAD

**Issue by Kim-Young-Joon** [Kim-Young-Joon/mini-project#1]
프로젝트 생성하기
 * [x] start.spring.io 활용
 * [x] 버전 정하기
 * [x] Dependency 추가하기

**Comment by jjiwoning** [comment]
![Image](https://user-images.githubusercontent.com/88527476/184605067-59673c9a-856f-4010-9b55-61012a5ddcbf.PNG)

**Comment by Kim-Young-Joon** [comment]
프로젝트 생성 완료
